#!/usr/bin/env python3
"""Regenerate local-key.js from .env.local.

Both files are gitignored and neither is deployed. app.js loads local-key.js
only when the page is on localhost, so that local work does not need the API
key typed into Settings every time browser storage is cleared.

Run it after rotating the key:

    python3 make-local-key.py

This script itself holds no secret and is safe to commit.
"""

import os
import stat
import sys

ENV = '.env.local'
OUT = 'local-key.js'

HEADER = """/* Generated by make-local-key.py from .env.local.
   Gitignored; never deployed.

   app.js loads this only when the page is on localhost. Its whole job is to
   save typing the key into Settings during local work. Delete this file to
   test the no-key path.

   After rotating the key, edit .env.local and run:

       python3 make-local-key.py
*/

"""


def read_env(path):
    if not os.path.exists(path):
        sys.exit(
            path + ' not found.\n'
            'Create it with a line reading ANTHROPIC_API_KEY=sk-ant-...\n'
            'It is gitignored, so it never leaves this machine.'
        )
    values = {}
    with open(path) as fh:
        for line in fh:
            line = line.strip()
            if not line or line.startswith('#') or '=' not in line:
                continue
            name, value = line.split('=', 1)
            values[name.strip()] = value.strip()
    return values


def main():
    values = read_env(ENV)
    key = values.get('ANTHROPIC_API_KEY', '')
    if not key:
        sys.exit('No ANTHROPIC_API_KEY in ' + ENV + '.')
    model = values.get('ANTHROPIC_MODEL', 'claude-sonnet-5')

    with open(OUT, 'w') as fh:
        fh.write(HEADER)
        fh.write("window.THINKING_APP_LOCAL_KEY = '" + key + "';\n")
        fh.write("window.THINKING_APP_LOCAL_MODEL = '" + model + "';\n")

    # Owner only. The key is in there in plain text.
    os.chmod(OUT, stat.S_IRUSR | stat.S_IWUSR)

    print('wrote ' + OUT + ' for model ' + model +
          ', key ending ' + key[-6:] + '. Not committed; see .gitignore.')


if __name__ == '__main__':
    main()
